name: memgpt-experiments
services:
  pgvector_db:
    image: ankane/pgvector:latest
    environment:
      # replace with actual values
      - POSTGRES_USER=memgpt
      - POSTGRES_PASSWORD=memgpt
      - POSTGRES_DB=memgpt
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local